# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
#  - name: Bio
  - name: About
    url: /
    weight: 99
#  - name: Publications
  - name: Research and Development
    url: /research/
#    url: /#papers
    weight: 30
# - name: Talks
# - name: Events
#   url: /#talks
#   weight: 80
# - name: News
#   url: /#news
#   weight: 90
  - name: Experience
    url: experience/
    weight: 20
  - name: Projects
    url: projects/
    weight: 10
#  - name: Teaching
#    url: teaching/
#    weight: 40
  - name: Privacy Policy
    url: /privacy/
    weight: 50
  - name: Terms of Service
    url: /terms/
    weight: 51
  - name: Legal Notice
    url: /legal/
    weight: 52